// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BaseProtocol.proto

package com.requestBroker;

public final class BaseProtocol {
  private BaseProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface dzhProcotolOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol.dzhProcotol)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 protocolNo = 1;</code>
     */
    boolean hasProtocolNo();
    /**
     * <code>required int32 protocolNo = 1;</code>
     */
    int getProtocolNo();

    /**
     * <code>optional .protocol.dzhProcotol.QueryContracts queryContracts = 2;</code>
     */
    boolean hasQueryContracts();
    /**
     * <code>optional .protocol.dzhProcotol.QueryContracts queryContracts = 2;</code>
     */
    com.requestBroker.BaseProtocol.dzhProcotol.QueryContracts getQueryContracts();
    /**
     * <code>optional .protocol.dzhProcotol.QueryContracts queryContracts = 2;</code>
     */
    com.requestBroker.BaseProtocol.dzhProcotol.QueryContractsOrBuilder getQueryContractsOrBuilder();

    /**
     * <code>optional .protocol.dzhProcotol.MakeOrder makeOrder = 3;</code>
     */
    boolean hasMakeOrder();
    /**
     * <code>optional .protocol.dzhProcotol.MakeOrder makeOrder = 3;</code>
     */
    com.requestBroker.BaseProtocol.dzhProcotol.MakeOrder getMakeOrder();
    /**
     * <code>optional .protocol.dzhProcotol.MakeOrder makeOrder = 3;</code>
     */
    com.requestBroker.BaseProtocol.dzhProcotol.MakeOrderOrBuilder getMakeOrderOrBuilder();
  }
  /**
   * Protobuf type {@code protocol.dzhProcotol}
   */
  public static final class dzhProcotol extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protocol.dzhProcotol)
      dzhProcotolOrBuilder {
    // Use dzhProcotol.newBuilder() to construct.
    private dzhProcotol(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private dzhProcotol(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final dzhProcotol defaultInstance;
    public static dzhProcotol getDefaultInstance() {
      return defaultInstance;
    }

    public dzhProcotol getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private dzhProcotol(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              protocolNo_ = input.readInt32();
              break;
            }
            case 18: {
              com.requestBroker.BaseProtocol.dzhProcotol.QueryContracts.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = queryContracts_.toBuilder();
              }
              queryContracts_ = input.readMessage(com.requestBroker.BaseProtocol.dzhProcotol.QueryContracts.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(queryContracts_);
                queryContracts_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 26: {
              com.requestBroker.BaseProtocol.dzhProcotol.MakeOrder.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = makeOrder_.toBuilder();
              }
              makeOrder_ = input.readMessage(com.requestBroker.BaseProtocol.dzhProcotol.MakeOrder.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(makeOrder_);
                makeOrder_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.requestBroker.BaseProtocol.internal_static_protocol_dzhProcotol_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.requestBroker.BaseProtocol.internal_static_protocol_dzhProcotol_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.requestBroker.BaseProtocol.dzhProcotol.class, com.requestBroker.BaseProtocol.dzhProcotol.Builder.class);
    }

    public static com.google.protobuf.Parser<dzhProcotol> PARSER =
        new com.google.protobuf.AbstractParser<dzhProcotol>() {
      public dzhProcotol parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new dzhProcotol(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<dzhProcotol> getParserForType() {
      return PARSER;
    }

    public interface QueryContractsOrBuilder extends
        // @@protoc_insertion_point(interface_extends:protocol.dzhProcotol.QueryContracts)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>optional string code = 1;</code>
       */
      boolean hasCode();
      /**
       * <code>optional string code = 1;</code>
       */
      java.lang.String getCode();
      /**
       * <code>optional string code = 1;</code>
       */
      com.google.protobuf.ByteString
          getCodeBytes();

      /**
       * <code>optional string name = 2;</code>
       */
      boolean hasName();
      /**
       * <code>optional string name = 2;</code>
       */
      java.lang.String getName();
      /**
       * <code>optional string name = 2;</code>
       */
      com.google.protobuf.ByteString
          getNameBytes();
    }
    /**
     * Protobuf type {@code protocol.dzhProcotol.QueryContracts}
     */
    public static final class QueryContracts extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:protocol.dzhProcotol.QueryContracts)
        QueryContractsOrBuilder {
      // Use QueryContracts.newBuilder() to construct.
      private QueryContracts(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private QueryContracts(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final QueryContracts defaultInstance;
      public static QueryContracts getDefaultInstance() {
        return defaultInstance;
      }

      public QueryContracts getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private QueryContracts(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000001;
                code_ = bs;
                break;
              }
              case 18: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000002;
                name_ = bs;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.requestBroker.BaseProtocol.internal_static_protocol_dzhProcotol_QueryContracts_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.requestBroker.BaseProtocol.internal_static_protocol_dzhProcotol_QueryContracts_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.requestBroker.BaseProtocol.dzhProcotol.QueryContracts.class, com.requestBroker.BaseProtocol.dzhProcotol.QueryContracts.Builder.class);
      }

      public static com.google.protobuf.Parser<QueryContracts> PARSER =
          new com.google.protobuf.AbstractParser<QueryContracts>() {
        public QueryContracts parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new QueryContracts(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<QueryContracts> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      public static final int CODE_FIELD_NUMBER = 1;
      private java.lang.Object code_;
      /**
       * <code>optional string code = 1;</code>
       */
      public boolean hasCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string code = 1;</code>
       */
      public java.lang.String getCode() {
        java.lang.Object ref = code_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            code_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string code = 1;</code>
       */
      public com.google.protobuf.ByteString
          getCodeBytes() {
        java.lang.Object ref = code_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          code_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int NAME_FIELD_NUMBER = 2;
      private java.lang.Object name_;
      /**
       * <code>optional string name = 2;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private void initFields() {
        code_ = "";
        name_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getCodeBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getNameBytes());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getCodeBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getNameBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.requestBroker.BaseProtocol.dzhProcotol.QueryContracts parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.requestBroker.BaseProtocol.dzhProcotol.QueryContracts parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.requestBroker.BaseProtocol.dzhProcotol.QueryContracts parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.requestBroker.BaseProtocol.dzhProcotol.QueryContracts parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.requestBroker.BaseProtocol.dzhProcotol.QueryContracts parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.requestBroker.BaseProtocol.dzhProcotol.QueryContracts parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.requestBroker.BaseProtocol.dzhProcotol.QueryContracts parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.requestBroker.BaseProtocol.dzhProcotol.QueryContracts parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.requestBroker.BaseProtocol.dzhProcotol.QueryContracts parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.requestBroker.BaseProtocol.dzhProcotol.QueryContracts parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.requestBroker.BaseProtocol.dzhProcotol.QueryContracts prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code protocol.dzhProcotol.QueryContracts}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:protocol.dzhProcotol.QueryContracts)
          com.requestBroker.BaseProtocol.dzhProcotol.QueryContractsOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.requestBroker.BaseProtocol.internal_static_protocol_dzhProcotol_QueryContracts_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.requestBroker.BaseProtocol.internal_static_protocol_dzhProcotol_QueryContracts_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.requestBroker.BaseProtocol.dzhProcotol.QueryContracts.class, com.requestBroker.BaseProtocol.dzhProcotol.QueryContracts.Builder.class);
        }

        // Construct using com.requestBroker.BaseProtocol.dzhProcotol.QueryContracts.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          code_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          name_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.requestBroker.BaseProtocol.internal_static_protocol_dzhProcotol_QueryContracts_descriptor;
        }

        public com.requestBroker.BaseProtocol.dzhProcotol.QueryContracts getDefaultInstanceForType() {
          return com.requestBroker.BaseProtocol.dzhProcotol.QueryContracts.getDefaultInstance();
        }

        public com.requestBroker.BaseProtocol.dzhProcotol.QueryContracts build() {
          com.requestBroker.BaseProtocol.dzhProcotol.QueryContracts result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.requestBroker.BaseProtocol.dzhProcotol.QueryContracts buildPartial() {
          com.requestBroker.BaseProtocol.dzhProcotol.QueryContracts result = new com.requestBroker.BaseProtocol.dzhProcotol.QueryContracts(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.code_ = code_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.name_ = name_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.requestBroker.BaseProtocol.dzhProcotol.QueryContracts) {
            return mergeFrom((com.requestBroker.BaseProtocol.dzhProcotol.QueryContracts)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.requestBroker.BaseProtocol.dzhProcotol.QueryContracts other) {
          if (other == com.requestBroker.BaseProtocol.dzhProcotol.QueryContracts.getDefaultInstance()) return this;
          if (other.hasCode()) {
            bitField0_ |= 0x00000001;
            code_ = other.code_;
            onChanged();
          }
          if (other.hasName()) {
            bitField0_ |= 0x00000002;
            name_ = other.name_;
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.requestBroker.BaseProtocol.dzhProcotol.QueryContracts parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.requestBroker.BaseProtocol.dzhProcotol.QueryContracts) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private java.lang.Object code_ = "";
        /**
         * <code>optional string code = 1;</code>
         */
        public boolean hasCode() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>optional string code = 1;</code>
         */
        public java.lang.String getCode() {
          java.lang.Object ref = code_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              code_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string code = 1;</code>
         */
        public com.google.protobuf.ByteString
            getCodeBytes() {
          java.lang.Object ref = code_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            code_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string code = 1;</code>
         */
        public Builder setCode(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          code_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string code = 1;</code>
         */
        public Builder clearCode() {
          bitField0_ = (bitField0_ & ~0x00000001);
          code_ = getDefaultInstance().getCode();
          onChanged();
          return this;
        }
        /**
         * <code>optional string code = 1;</code>
         */
        public Builder setCodeBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          code_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object name_ = "";
        /**
         * <code>optional string name = 2;</code>
         */
        public boolean hasName() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional string name = 2;</code>
         */
        public java.lang.String getName() {
          java.lang.Object ref = name_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              name_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string name = 2;</code>
         */
        public com.google.protobuf.ByteString
            getNameBytes() {
          java.lang.Object ref = name_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            name_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string name = 2;</code>
         */
        public Builder setName(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          name_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string name = 2;</code>
         */
        public Builder clearName() {
          bitField0_ = (bitField0_ & ~0x00000002);
          name_ = getDefaultInstance().getName();
          onChanged();
          return this;
        }
        /**
         * <code>optional string name = 2;</code>
         */
        public Builder setNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          name_ = value;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:protocol.dzhProcotol.QueryContracts)
      }

      static {
        defaultInstance = new QueryContracts(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:protocol.dzhProcotol.QueryContracts)
    }

    public interface MakeOrderOrBuilder extends
        // @@protoc_insertion_point(interface_extends:protocol.dzhProcotol.MakeOrder)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>optional string code = 1;</code>
       */
      boolean hasCode();
      /**
       * <code>optional string code = 1;</code>
       */
      java.lang.String getCode();
      /**
       * <code>optional string code = 1;</code>
       */
      com.google.protobuf.ByteString
          getCodeBytes();

      /**
       * <code>optional string name = 2;</code>
       */
      boolean hasName();
      /**
       * <code>optional string name = 2;</code>
       */
      java.lang.String getName();
      /**
       * <code>optional string name = 2;</code>
       */
      com.google.protobuf.ByteString
          getNameBytes();
    }
    /**
     * Protobuf type {@code protocol.dzhProcotol.MakeOrder}
     */
    public static final class MakeOrder extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:protocol.dzhProcotol.MakeOrder)
        MakeOrderOrBuilder {
      // Use MakeOrder.newBuilder() to construct.
      private MakeOrder(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private MakeOrder(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final MakeOrder defaultInstance;
      public static MakeOrder getDefaultInstance() {
        return defaultInstance;
      }

      public MakeOrder getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private MakeOrder(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000001;
                code_ = bs;
                break;
              }
              case 18: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000002;
                name_ = bs;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.requestBroker.BaseProtocol.internal_static_protocol_dzhProcotol_MakeOrder_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.requestBroker.BaseProtocol.internal_static_protocol_dzhProcotol_MakeOrder_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.requestBroker.BaseProtocol.dzhProcotol.MakeOrder.class, com.requestBroker.BaseProtocol.dzhProcotol.MakeOrder.Builder.class);
      }

      public static com.google.protobuf.Parser<MakeOrder> PARSER =
          new com.google.protobuf.AbstractParser<MakeOrder>() {
        public MakeOrder parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new MakeOrder(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<MakeOrder> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      public static final int CODE_FIELD_NUMBER = 1;
      private java.lang.Object code_;
      /**
       * <code>optional string code = 1;</code>
       */
      public boolean hasCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string code = 1;</code>
       */
      public java.lang.String getCode() {
        java.lang.Object ref = code_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            code_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string code = 1;</code>
       */
      public com.google.protobuf.ByteString
          getCodeBytes() {
        java.lang.Object ref = code_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          code_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int NAME_FIELD_NUMBER = 2;
      private java.lang.Object name_;
      /**
       * <code>optional string name = 2;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private void initFields() {
        code_ = "";
        name_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getCodeBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getNameBytes());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getCodeBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getNameBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.requestBroker.BaseProtocol.dzhProcotol.MakeOrder parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.requestBroker.BaseProtocol.dzhProcotol.MakeOrder parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.requestBroker.BaseProtocol.dzhProcotol.MakeOrder parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.requestBroker.BaseProtocol.dzhProcotol.MakeOrder parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.requestBroker.BaseProtocol.dzhProcotol.MakeOrder parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.requestBroker.BaseProtocol.dzhProcotol.MakeOrder parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.requestBroker.BaseProtocol.dzhProcotol.MakeOrder parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.requestBroker.BaseProtocol.dzhProcotol.MakeOrder parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.requestBroker.BaseProtocol.dzhProcotol.MakeOrder parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.requestBroker.BaseProtocol.dzhProcotol.MakeOrder parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.requestBroker.BaseProtocol.dzhProcotol.MakeOrder prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code protocol.dzhProcotol.MakeOrder}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:protocol.dzhProcotol.MakeOrder)
          com.requestBroker.BaseProtocol.dzhProcotol.MakeOrderOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.requestBroker.BaseProtocol.internal_static_protocol_dzhProcotol_MakeOrder_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.requestBroker.BaseProtocol.internal_static_protocol_dzhProcotol_MakeOrder_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.requestBroker.BaseProtocol.dzhProcotol.MakeOrder.class, com.requestBroker.BaseProtocol.dzhProcotol.MakeOrder.Builder.class);
        }

        // Construct using com.requestBroker.BaseProtocol.dzhProcotol.MakeOrder.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          code_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          name_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.requestBroker.BaseProtocol.internal_static_protocol_dzhProcotol_MakeOrder_descriptor;
        }

        public com.requestBroker.BaseProtocol.dzhProcotol.MakeOrder getDefaultInstanceForType() {
          return com.requestBroker.BaseProtocol.dzhProcotol.MakeOrder.getDefaultInstance();
        }

        public com.requestBroker.BaseProtocol.dzhProcotol.MakeOrder build() {
          com.requestBroker.BaseProtocol.dzhProcotol.MakeOrder result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.requestBroker.BaseProtocol.dzhProcotol.MakeOrder buildPartial() {
          com.requestBroker.BaseProtocol.dzhProcotol.MakeOrder result = new com.requestBroker.BaseProtocol.dzhProcotol.MakeOrder(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.code_ = code_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.name_ = name_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.requestBroker.BaseProtocol.dzhProcotol.MakeOrder) {
            return mergeFrom((com.requestBroker.BaseProtocol.dzhProcotol.MakeOrder)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.requestBroker.BaseProtocol.dzhProcotol.MakeOrder other) {
          if (other == com.requestBroker.BaseProtocol.dzhProcotol.MakeOrder.getDefaultInstance()) return this;
          if (other.hasCode()) {
            bitField0_ |= 0x00000001;
            code_ = other.code_;
            onChanged();
          }
          if (other.hasName()) {
            bitField0_ |= 0x00000002;
            name_ = other.name_;
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.requestBroker.BaseProtocol.dzhProcotol.MakeOrder parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.requestBroker.BaseProtocol.dzhProcotol.MakeOrder) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private java.lang.Object code_ = "";
        /**
         * <code>optional string code = 1;</code>
         */
        public boolean hasCode() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>optional string code = 1;</code>
         */
        public java.lang.String getCode() {
          java.lang.Object ref = code_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              code_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string code = 1;</code>
         */
        public com.google.protobuf.ByteString
            getCodeBytes() {
          java.lang.Object ref = code_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            code_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string code = 1;</code>
         */
        public Builder setCode(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          code_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string code = 1;</code>
         */
        public Builder clearCode() {
          bitField0_ = (bitField0_ & ~0x00000001);
          code_ = getDefaultInstance().getCode();
          onChanged();
          return this;
        }
        /**
         * <code>optional string code = 1;</code>
         */
        public Builder setCodeBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          code_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object name_ = "";
        /**
         * <code>optional string name = 2;</code>
         */
        public boolean hasName() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional string name = 2;</code>
         */
        public java.lang.String getName() {
          java.lang.Object ref = name_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              name_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string name = 2;</code>
         */
        public com.google.protobuf.ByteString
            getNameBytes() {
          java.lang.Object ref = name_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            name_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string name = 2;</code>
         */
        public Builder setName(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          name_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string name = 2;</code>
         */
        public Builder clearName() {
          bitField0_ = (bitField0_ & ~0x00000002);
          name_ = getDefaultInstance().getName();
          onChanged();
          return this;
        }
        /**
         * <code>optional string name = 2;</code>
         */
        public Builder setNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          name_ = value;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:protocol.dzhProcotol.MakeOrder)
      }

      static {
        defaultInstance = new MakeOrder(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:protocol.dzhProcotol.MakeOrder)
    }

    private int bitField0_;
    public static final int PROTOCOLNO_FIELD_NUMBER = 1;
    private int protocolNo_;
    /**
     * <code>required int32 protocolNo = 1;</code>
     */
    public boolean hasProtocolNo() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 protocolNo = 1;</code>
     */
    public int getProtocolNo() {
      return protocolNo_;
    }

    public static final int QUERYCONTRACTS_FIELD_NUMBER = 2;
    private com.requestBroker.BaseProtocol.dzhProcotol.QueryContracts queryContracts_;
    /**
     * <code>optional .protocol.dzhProcotol.QueryContracts queryContracts = 2;</code>
     */
    public boolean hasQueryContracts() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .protocol.dzhProcotol.QueryContracts queryContracts = 2;</code>
     */
    public com.requestBroker.BaseProtocol.dzhProcotol.QueryContracts getQueryContracts() {
      return queryContracts_;
    }
    /**
     * <code>optional .protocol.dzhProcotol.QueryContracts queryContracts = 2;</code>
     */
    public com.requestBroker.BaseProtocol.dzhProcotol.QueryContractsOrBuilder getQueryContractsOrBuilder() {
      return queryContracts_;
    }

    public static final int MAKEORDER_FIELD_NUMBER = 3;
    private com.requestBroker.BaseProtocol.dzhProcotol.MakeOrder makeOrder_;
    /**
     * <code>optional .protocol.dzhProcotol.MakeOrder makeOrder = 3;</code>
     */
    public boolean hasMakeOrder() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .protocol.dzhProcotol.MakeOrder makeOrder = 3;</code>
     */
    public com.requestBroker.BaseProtocol.dzhProcotol.MakeOrder getMakeOrder() {
      return makeOrder_;
    }
    /**
     * <code>optional .protocol.dzhProcotol.MakeOrder makeOrder = 3;</code>
     */
    public com.requestBroker.BaseProtocol.dzhProcotol.MakeOrderOrBuilder getMakeOrderOrBuilder() {
      return makeOrder_;
    }

    private void initFields() {
      protocolNo_ = 0;
      queryContracts_ = com.requestBroker.BaseProtocol.dzhProcotol.QueryContracts.getDefaultInstance();
      makeOrder_ = com.requestBroker.BaseProtocol.dzhProcotol.MakeOrder.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasProtocolNo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, protocolNo_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, queryContracts_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, makeOrder_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, protocolNo_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, queryContracts_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, makeOrder_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.requestBroker.BaseProtocol.dzhProcotol parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.requestBroker.BaseProtocol.dzhProcotol parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.requestBroker.BaseProtocol.dzhProcotol parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.requestBroker.BaseProtocol.dzhProcotol parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.requestBroker.BaseProtocol.dzhProcotol parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.requestBroker.BaseProtocol.dzhProcotol parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.requestBroker.BaseProtocol.dzhProcotol parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.requestBroker.BaseProtocol.dzhProcotol parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.requestBroker.BaseProtocol.dzhProcotol parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.requestBroker.BaseProtocol.dzhProcotol parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.requestBroker.BaseProtocol.dzhProcotol prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol.dzhProcotol}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol.dzhProcotol)
        com.requestBroker.BaseProtocol.dzhProcotolOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.requestBroker.BaseProtocol.internal_static_protocol_dzhProcotol_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.requestBroker.BaseProtocol.internal_static_protocol_dzhProcotol_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.requestBroker.BaseProtocol.dzhProcotol.class, com.requestBroker.BaseProtocol.dzhProcotol.Builder.class);
      }

      // Construct using com.requestBroker.BaseProtocol.dzhProcotol.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getQueryContractsFieldBuilder();
          getMakeOrderFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        protocolNo_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (queryContractsBuilder_ == null) {
          queryContracts_ = com.requestBroker.BaseProtocol.dzhProcotol.QueryContracts.getDefaultInstance();
        } else {
          queryContractsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (makeOrderBuilder_ == null) {
          makeOrder_ = com.requestBroker.BaseProtocol.dzhProcotol.MakeOrder.getDefaultInstance();
        } else {
          makeOrderBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.requestBroker.BaseProtocol.internal_static_protocol_dzhProcotol_descriptor;
      }

      public com.requestBroker.BaseProtocol.dzhProcotol getDefaultInstanceForType() {
        return com.requestBroker.BaseProtocol.dzhProcotol.getDefaultInstance();
      }

      public com.requestBroker.BaseProtocol.dzhProcotol build() {
        com.requestBroker.BaseProtocol.dzhProcotol result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.requestBroker.BaseProtocol.dzhProcotol buildPartial() {
        com.requestBroker.BaseProtocol.dzhProcotol result = new com.requestBroker.BaseProtocol.dzhProcotol(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.protocolNo_ = protocolNo_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (queryContractsBuilder_ == null) {
          result.queryContracts_ = queryContracts_;
        } else {
          result.queryContracts_ = queryContractsBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (makeOrderBuilder_ == null) {
          result.makeOrder_ = makeOrder_;
        } else {
          result.makeOrder_ = makeOrderBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.requestBroker.BaseProtocol.dzhProcotol) {
          return mergeFrom((com.requestBroker.BaseProtocol.dzhProcotol)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.requestBroker.BaseProtocol.dzhProcotol other) {
        if (other == com.requestBroker.BaseProtocol.dzhProcotol.getDefaultInstance()) return this;
        if (other.hasProtocolNo()) {
          setProtocolNo(other.getProtocolNo());
        }
        if (other.hasQueryContracts()) {
          mergeQueryContracts(other.getQueryContracts());
        }
        if (other.hasMakeOrder()) {
          mergeMakeOrder(other.getMakeOrder());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasProtocolNo()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.requestBroker.BaseProtocol.dzhProcotol parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.requestBroker.BaseProtocol.dzhProcotol) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int protocolNo_ ;
      /**
       * <code>required int32 protocolNo = 1;</code>
       */
      public boolean hasProtocolNo() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 protocolNo = 1;</code>
       */
      public int getProtocolNo() {
        return protocolNo_;
      }
      /**
       * <code>required int32 protocolNo = 1;</code>
       */
      public Builder setProtocolNo(int value) {
        bitField0_ |= 0x00000001;
        protocolNo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 protocolNo = 1;</code>
       */
      public Builder clearProtocolNo() {
        bitField0_ = (bitField0_ & ~0x00000001);
        protocolNo_ = 0;
        onChanged();
        return this;
      }

      private com.requestBroker.BaseProtocol.dzhProcotol.QueryContracts queryContracts_ = com.requestBroker.BaseProtocol.dzhProcotol.QueryContracts.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.requestBroker.BaseProtocol.dzhProcotol.QueryContracts, com.requestBroker.BaseProtocol.dzhProcotol.QueryContracts.Builder, com.requestBroker.BaseProtocol.dzhProcotol.QueryContractsOrBuilder> queryContractsBuilder_;
      /**
       * <code>optional .protocol.dzhProcotol.QueryContracts queryContracts = 2;</code>
       */
      public boolean hasQueryContracts() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .protocol.dzhProcotol.QueryContracts queryContracts = 2;</code>
       */
      public com.requestBroker.BaseProtocol.dzhProcotol.QueryContracts getQueryContracts() {
        if (queryContractsBuilder_ == null) {
          return queryContracts_;
        } else {
          return queryContractsBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .protocol.dzhProcotol.QueryContracts queryContracts = 2;</code>
       */
      public Builder setQueryContracts(com.requestBroker.BaseProtocol.dzhProcotol.QueryContracts value) {
        if (queryContractsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          queryContracts_ = value;
          onChanged();
        } else {
          queryContractsBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .protocol.dzhProcotol.QueryContracts queryContracts = 2;</code>
       */
      public Builder setQueryContracts(
          com.requestBroker.BaseProtocol.dzhProcotol.QueryContracts.Builder builderForValue) {
        if (queryContractsBuilder_ == null) {
          queryContracts_ = builderForValue.build();
          onChanged();
        } else {
          queryContractsBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .protocol.dzhProcotol.QueryContracts queryContracts = 2;</code>
       */
      public Builder mergeQueryContracts(com.requestBroker.BaseProtocol.dzhProcotol.QueryContracts value) {
        if (queryContractsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              queryContracts_ != com.requestBroker.BaseProtocol.dzhProcotol.QueryContracts.getDefaultInstance()) {
            queryContracts_ =
              com.requestBroker.BaseProtocol.dzhProcotol.QueryContracts.newBuilder(queryContracts_).mergeFrom(value).buildPartial();
          } else {
            queryContracts_ = value;
          }
          onChanged();
        } else {
          queryContractsBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .protocol.dzhProcotol.QueryContracts queryContracts = 2;</code>
       */
      public Builder clearQueryContracts() {
        if (queryContractsBuilder_ == null) {
          queryContracts_ = com.requestBroker.BaseProtocol.dzhProcotol.QueryContracts.getDefaultInstance();
          onChanged();
        } else {
          queryContractsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .protocol.dzhProcotol.QueryContracts queryContracts = 2;</code>
       */
      public com.requestBroker.BaseProtocol.dzhProcotol.QueryContracts.Builder getQueryContractsBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getQueryContractsFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .protocol.dzhProcotol.QueryContracts queryContracts = 2;</code>
       */
      public com.requestBroker.BaseProtocol.dzhProcotol.QueryContractsOrBuilder getQueryContractsOrBuilder() {
        if (queryContractsBuilder_ != null) {
          return queryContractsBuilder_.getMessageOrBuilder();
        } else {
          return queryContracts_;
        }
      }
      /**
       * <code>optional .protocol.dzhProcotol.QueryContracts queryContracts = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.requestBroker.BaseProtocol.dzhProcotol.QueryContracts, com.requestBroker.BaseProtocol.dzhProcotol.QueryContracts.Builder, com.requestBroker.BaseProtocol.dzhProcotol.QueryContractsOrBuilder> 
          getQueryContractsFieldBuilder() {
        if (queryContractsBuilder_ == null) {
          queryContractsBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.requestBroker.BaseProtocol.dzhProcotol.QueryContracts, com.requestBroker.BaseProtocol.dzhProcotol.QueryContracts.Builder, com.requestBroker.BaseProtocol.dzhProcotol.QueryContractsOrBuilder>(
                  getQueryContracts(),
                  getParentForChildren(),
                  isClean());
          queryContracts_ = null;
        }
        return queryContractsBuilder_;
      }

      private com.requestBroker.BaseProtocol.dzhProcotol.MakeOrder makeOrder_ = com.requestBroker.BaseProtocol.dzhProcotol.MakeOrder.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.requestBroker.BaseProtocol.dzhProcotol.MakeOrder, com.requestBroker.BaseProtocol.dzhProcotol.MakeOrder.Builder, com.requestBroker.BaseProtocol.dzhProcotol.MakeOrderOrBuilder> makeOrderBuilder_;
      /**
       * <code>optional .protocol.dzhProcotol.MakeOrder makeOrder = 3;</code>
       */
      public boolean hasMakeOrder() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .protocol.dzhProcotol.MakeOrder makeOrder = 3;</code>
       */
      public com.requestBroker.BaseProtocol.dzhProcotol.MakeOrder getMakeOrder() {
        if (makeOrderBuilder_ == null) {
          return makeOrder_;
        } else {
          return makeOrderBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .protocol.dzhProcotol.MakeOrder makeOrder = 3;</code>
       */
      public Builder setMakeOrder(com.requestBroker.BaseProtocol.dzhProcotol.MakeOrder value) {
        if (makeOrderBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          makeOrder_ = value;
          onChanged();
        } else {
          makeOrderBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .protocol.dzhProcotol.MakeOrder makeOrder = 3;</code>
       */
      public Builder setMakeOrder(
          com.requestBroker.BaseProtocol.dzhProcotol.MakeOrder.Builder builderForValue) {
        if (makeOrderBuilder_ == null) {
          makeOrder_ = builderForValue.build();
          onChanged();
        } else {
          makeOrderBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .protocol.dzhProcotol.MakeOrder makeOrder = 3;</code>
       */
      public Builder mergeMakeOrder(com.requestBroker.BaseProtocol.dzhProcotol.MakeOrder value) {
        if (makeOrderBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              makeOrder_ != com.requestBroker.BaseProtocol.dzhProcotol.MakeOrder.getDefaultInstance()) {
            makeOrder_ =
              com.requestBroker.BaseProtocol.dzhProcotol.MakeOrder.newBuilder(makeOrder_).mergeFrom(value).buildPartial();
          } else {
            makeOrder_ = value;
          }
          onChanged();
        } else {
          makeOrderBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .protocol.dzhProcotol.MakeOrder makeOrder = 3;</code>
       */
      public Builder clearMakeOrder() {
        if (makeOrderBuilder_ == null) {
          makeOrder_ = com.requestBroker.BaseProtocol.dzhProcotol.MakeOrder.getDefaultInstance();
          onChanged();
        } else {
          makeOrderBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .protocol.dzhProcotol.MakeOrder makeOrder = 3;</code>
       */
      public com.requestBroker.BaseProtocol.dzhProcotol.MakeOrder.Builder getMakeOrderBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getMakeOrderFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .protocol.dzhProcotol.MakeOrder makeOrder = 3;</code>
       */
      public com.requestBroker.BaseProtocol.dzhProcotol.MakeOrderOrBuilder getMakeOrderOrBuilder() {
        if (makeOrderBuilder_ != null) {
          return makeOrderBuilder_.getMessageOrBuilder();
        } else {
          return makeOrder_;
        }
      }
      /**
       * <code>optional .protocol.dzhProcotol.MakeOrder makeOrder = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.requestBroker.BaseProtocol.dzhProcotol.MakeOrder, com.requestBroker.BaseProtocol.dzhProcotol.MakeOrder.Builder, com.requestBroker.BaseProtocol.dzhProcotol.MakeOrderOrBuilder> 
          getMakeOrderFieldBuilder() {
        if (makeOrderBuilder_ == null) {
          makeOrderBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.requestBroker.BaseProtocol.dzhProcotol.MakeOrder, com.requestBroker.BaseProtocol.dzhProcotol.MakeOrder.Builder, com.requestBroker.BaseProtocol.dzhProcotol.MakeOrderOrBuilder>(
                  getMakeOrder(),
                  getParentForChildren(),
                  isClean());
          makeOrder_ = null;
        }
        return makeOrderBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:protocol.dzhProcotol)
    }

    static {
      defaultInstance = new dzhProcotol(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protocol.dzhProcotol)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_dzhProcotol_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_dzhProcotol_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_dzhProcotol_QueryContracts_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_dzhProcotol_QueryContracts_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_dzhProcotol_MakeOrder_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_dzhProcotol_MakeOrder_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022BaseProtocol.proto\022\010protocol\"\352\001\n\013dzhPr" +
      "ocotol\022\022\n\nprotocolNo\030\001 \002(\005\022<\n\016queryContr" +
      "acts\030\002 \001(\0132$.protocol.dzhProcotol.QueryC" +
      "ontracts\0222\n\tmakeOrder\030\003 \001(\0132\037.protocol.d" +
      "zhProcotol.MakeOrder\032,\n\016QueryContracts\022\014" +
      "\n\004code\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\032\'\n\tMakeOrder\022" +
      "\014\n\004code\030\001 \001(\t\022\014\n\004name\030\002 \001(\tB\027\n\007com.requestBrokerB\014" +
      "BaseProtocol"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protocol_dzhProcotol_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protocol_dzhProcotol_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protocol_dzhProcotol_descriptor,
        new java.lang.String[] { "ProtocolNo", "QueryContracts", "MakeOrder", });
    internal_static_protocol_dzhProcotol_QueryContracts_descriptor =
      internal_static_protocol_dzhProcotol_descriptor.getNestedTypes().get(0);
    internal_static_protocol_dzhProcotol_QueryContracts_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protocol_dzhProcotol_QueryContracts_descriptor,
        new java.lang.String[] { "Code", "Name", });
    internal_static_protocol_dzhProcotol_MakeOrder_descriptor =
      internal_static_protocol_dzhProcotol_descriptor.getNestedTypes().get(1);
    internal_static_protocol_dzhProcotol_MakeOrder_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protocol_dzhProcotol_MakeOrder_descriptor,
        new java.lang.String[] { "Code", "Name", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
